// DO NOT EDIT. This file is automatically generated.

export interface Alpha {
	A: number;
}

export interface Turtle {
	Color: Alpha;
	Direction: Direction;
	X: number;
	Y: number;
}

export type Direction = "up" | "down" | "left" | "right";
