// DO NOT EDIT. This file is automatically generated.

export interface Alpha {
	A: number;
}

export interface Turtle {
	Color: Alpha;
	Direction: Direction;
	X: number;
	Y: number;
}

export interface Turtle2 {
	Color: Alpha;
	Direction: Direction;
	X: number;
	Y: number;
}

export interface User {
	Name: string;
	Age: number;
}

export interface Pie {
	title: string;
	value: number;
}

export type Direction = "up" | "down" | "left" | "right";
